services:
  esp32-server:
    container_name: ESPServer
    image: ghcr.io/barabasistvanattila/esp32-camera-server:0.0.1
    ports:
      - 13379:8080
    env_file: stack.env
    security_opt:
      - no-new-privileges:true
    mem_limit: 1g
    cpu_shares: 100
    volumes:
      - /volume1/Shared/Media/ESP32Photos:/data/photos:rw
    restart: unless-stopped