#pragma once

/**
 * @file app_config.h
 * @brief Central application configuration — thin translation layer.
 *
 * Every knob here is derived from a CONFIG_ macro generated by Kconfig
 * (Kconfig.projbuild + sdkconfig.defaults).  No magic strings or numbers
 * live in this file; they all come from menuconfig.
 *
 * The only job of this header is to map CONFIG_* names to the internal
 * types used by our modules (e.g. framesize_t enum, camera_board_t enum),
 * so callers never #include sdkconfig.h directly.
 */

#include "sdkconfig.h"       /* generated CONFIG_* macros                   */
#include "camera_hal.h"      /* camera_board_t, pixformat_t, framesize_t    */
#include "image_uploader.h"  /* upload_method_t                             */

#ifdef __cplusplus
extern "C" {
#endif

/* ── WiFi ─────────────────────────────────────────────────────────────────── */

#define APP_WIFI_SSID       CONFIG_APP_WIFI_SSID
#define APP_WIFI_PASSWORD   CONFIG_APP_WIFI_PASSWORD
#define APP_WIFI_MAX_RETRY  CONFIG_APP_WIFI_MAX_RETRY

/* ── Camera — board preset ────────────────────────────────────────────────── */

#if   defined(CONFIG_APP_CAMERA_BOARD_AI_THINKER)
#   define APP_CAMERA_BOARD  CAMERA_BOARD_AI_THINKER
#elif defined(CONFIG_APP_CAMERA_BOARD_WROVER_KIT)
#   define APP_CAMERA_BOARD  CAMERA_BOARD_WROVER_KIT
#elif defined(CONFIG_APP_CAMERA_BOARD_ESP_EYE)
#   define APP_CAMERA_BOARD  CAMERA_BOARD_ESP_EYE
#elif defined(CONFIG_APP_CAMERA_BOARD_M5STACK_PSRAM)
#   define APP_CAMERA_BOARD  CAMERA_BOARD_M5STACK_PSRAM
#elif defined(CONFIG_APP_CAMERA_BOARD_CUSTOM)
#   define APP_CAMERA_BOARD  CAMERA_BOARD_CUSTOM
#else
#   error "No camera board selected — run idf.py menuconfig"
#endif

/* ── Camera — frame size ──────────────────────────────────────────────────── */

#if   defined(CONFIG_APP_CAMERA_FRAMESIZE_QQVGA)
#   define APP_CAMERA_FRAMESIZE  FRAMESIZE_QQVGA
#elif defined(CONFIG_APP_CAMERA_FRAMESIZE_QVGA)
#   define APP_CAMERA_FRAMESIZE  FRAMESIZE_QVGA
#elif defined(CONFIG_APP_CAMERA_FRAMESIZE_VGA)
#   define APP_CAMERA_FRAMESIZE  FRAMESIZE_VGA
#elif defined(CONFIG_APP_CAMERA_FRAMESIZE_SVGA)
#   define APP_CAMERA_FRAMESIZE  FRAMESIZE_SVGA
#elif defined(CONFIG_APP_CAMERA_FRAMESIZE_XGA)
#   define APP_CAMERA_FRAMESIZE  FRAMESIZE_XGA
#elif defined(CONFIG_APP_CAMERA_FRAMESIZE_HD)
#   define APP_CAMERA_FRAMESIZE  FRAMESIZE_HD
#elif defined(CONFIG_APP_CAMERA_FRAMESIZE_UXGA)
#   define APP_CAMERA_FRAMESIZE  FRAMESIZE_UXGA
#else
#   error "No frame size selected — run idf.py menuconfig"
#endif

/* ── Camera — image quality and buffers ──────────────────────────────────── */

#define APP_CAMERA_FORMAT    PIXFORMAT_JPEG   /* always JPEG for streaming   */
#define APP_CAMERA_QUALITY   CONFIG_APP_CAMERA_JPEG_QUALITY
#define APP_CAMERA_FB_COUNT  CONFIG_APP_CAMERA_FB_COUNT


/* ── Power management — WiFi power save ──────────────────────────────────── */

#if   defined(CONFIG_APP_POWER_SAVE_NONE)
#   define APP_WIFI_PS_MODE  WIFI_PS_NONE
#elif defined(CONFIG_APP_POWER_SAVE_MIN_MODEM)
#   define APP_WIFI_PS_MODE  WIFI_PS_MIN_MODEM
#elif defined(CONFIG_APP_POWER_SAVE_MAX_MODEM)
#   define APP_WIFI_PS_MODE  WIFI_PS_MAX_MODEM
#else
#   define APP_WIFI_PS_MODE  WIFI_PS_MIN_MODEM   /* safe default */
#endif

/* ── Power management — CPU frequency (only when PM_ENABLE is set) ───────── */

#ifdef CONFIG_PM_ENABLE
#   define APP_MAX_CPU_FREQ_MHZ  CONFIG_APP_MAX_CPU_FREQ_MHZ
#   define APP_MIN_CPU_FREQ_MHZ  CONFIG_APP_MIN_CPU_FREQ_MHZ
#endif

/* ── Cloud upload ─────────────────────────────────────────────────────────── */

#define APP_UPLOAD_ENDPOINT_URL    CONFIG_APP_UPLOAD_ENDPOINT_URL
#define APP_UPLOAD_RETRY_COUNT     CONFIG_APP_UPLOAD_RETRY_COUNT
#define APP_UPLOAD_TIMEOUT_MS      CONFIG_APP_UPLOAD_TIMEOUT_MS
#define APP_UPLOAD_CHUNK_SIZE      CONFIG_APP_UPLOAD_CHUNK_SIZE
#define APP_UPLOAD_SKIP_TLS_VERIFY CONFIG_APP_UPLOAD_SKIP_TLS_VERIFY
#define APP_UPLOAD_USERNAME        CONFIG_APP_UPLOAD_USERNAME
#define APP_UPLOAD_PASSWORD        CONFIG_APP_UPLOAD_PASSWORD
#define APP_UPLOAD_WINDOW_DAYS     CONFIG_APP_UPLOAD_WINDOW_DAYS

#if   defined(CONFIG_APP_UPLOAD_METHOD_PUT)
#   define APP_UPLOAD_METHOD  UPLOAD_METHOD_PUT
#elif defined(CONFIG_APP_UPLOAD_METHOD_POST)
#   define APP_UPLOAD_METHOD  UPLOAD_METHOD_POST
#else
#   define APP_UPLOAD_METHOD  UPLOAD_METHOD_PUT
#endif

/* ── NTP / SNTP ───────────────────────────────────────────────────────────── */

#define APP_SNTP_SERVER      CONFIG_APP_SNTP_SERVER
#define APP_SNTP_TIMEOUT_MS  CONFIG_APP_SNTP_TIMEOUT_MS
#define APP_TIMEZONE         CONFIG_APP_TIMEZONE

/* ── Wake and sleep schedule ──────────────────────────────────────────────── */

#define APP_DAILY_CHECK_HOUR    CONFIG_APP_DAILY_CHECK_HOUR
#define APP_DAILY_CHECK_MINUTE  CONFIG_APP_DAILY_CHECK_MINUTE

/* ── Test mode ────────────────────────────────────────────────────────────── */

/*
 * APP_TEST_UPLOAD_MODE is defined (value 1) only when the Kconfig flag is
 * enabled.  All test-mode branches in app_main.c are guarded with
 * #ifdef CONFIG_APP_TEST_UPLOAD_MODE so they compile away completely in
 * production builds — zero code size impact when disabled.
 */
#ifdef CONFIG_APP_TEST_UPLOAD_MODE
#   define APP_TEST_UPLOAD_MODE       1
#   define APP_TEST_UPLOAD_INTERVAL_S CONFIG_APP_TEST_UPLOAD_INTERVAL_S
#endif

#ifdef __cplusplus
}
#endif